export const pdfConstants ={
    ADD_NEW_PDF_REQUEST :"ADD_NEW_PDF_REQUEST",
    ADD_NEW_PDF_SUCCESS :"ADD_NEW_PDF_SUCCESS",
    ADD_NEW_PDF_ERROR :"ADD_NEW_PDF_ERROR",
}

export const languageConstants ={
    ADDNEW_LANGUAGE_REQUEST :"ADDNEW_LANGUAGE_REQUEST",
    ADDNEW_LANGUAGE_SUCCESS :"ADDNEW_LANGUAGE_SUCCESS",
    ADDNEW_LANGUAGE_ERROR :"ADDNEW_LANGUAGE_ERROR",
    GETALL_LANGUAGE_REQUEST :"GETALL_LANGUAGE_REQUEST",
    GETALL_LANGUAGE_SUCCESS :"GETALL_LANGUAGE_SUCCESS",
    GETALL_LANGUAGE_ERROR :"GETALL_LANGUAGE_ERROR",
    DELETE_LANGUAGE_REQUEST :"DELETE_LANGUAGE_REQUEST",
    DELETE_LANGUAGE_SUCCESS :"DELETE_LANGUAGE_SUCCESS",
    DELETE_LANGUAGE_ERROR :"DELETE_LANGUAGE_ERROR",
}

export const materialConstants ={
    ADDNEW_MATERIAL_REQUEST :"ADDNEW_MATERIAL_REQUEST",
    ADDNEW_MATERIAL_SUCCESS :"ADDNEW_MATERIAL_SUCCESS",
    ADDNEW_MATERIAL_ERROR :"ADDNEW_MATERIAL_ERROR",
    GETALL_MATERIAL_REQUEST :"GETALL_MATERIAL_REQUEST",
    GETALL_MATERIAL_SUCCESS :"GETALL_MATERIAL_SUCCESS",
    GETALL_MATERIAL_ERROR :"GETALL_MATERIAL_ERROR",
    DELETE_MATERIAL_REQUEST :"DELETE_MATERIAL_REQUEST",
    DELETE_MATERIAL_SUCCESS :"DELETE_MATERIAL_SUCCESS",
    DELETE_MATERIAL_ERROR :"DELETE_MATERIAL_ERROR",
}